// src/components/PostPreview/index.tsx
import { useState, useEffect, FC, useCallback } from "react";

import { addPostComment, getPostComments, removePostComment } from "api";

import { InputField } from "components";
import { TextAreaField } from "shared/TextAreaField";
import { createInitErrors } from "utils/createInitErrors";
import { Loader } from "shared/Loader";

interface Props {
  post: Posts.Data;
  onDeletePost: () => void;
  onEditPost: () => void;
}

const initErrors = createInitErrors(["name", "email", "body"]);

export const PostPreview: FC<Props> = ({ post, onDeletePost, onEditPost }) => {
  const [isFormOpen, setIsFormOpen] = useState(false);
  const [comments, setComments] = useState<Posts.Comment[]>([]);
  const [loadingComments, setLoadingComments] = useState(true);

  const [fields, setFields] = useState({
    name: "",
    email: "",
    body: "",
  });

  const [errors, setErrors] = useState(initErrors);

  useEffect(() => {
    (async () => {
      setLoadingComments(true);

      const comments = await getPostComments(post.id);

      comments && setComments(comments);

      setLoadingComments(false);
    })();
  }, [post.id]);

  const handleChangeInputValue = useCallback(
    (event: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => {
      setFields((prev) => ({
        ...prev,
        [event.target.name]: event.target.value,
      }));

      setErrors(initErrors);
    },
    []
  );

  const handleToggleOpenForm = useCallback(
    (value: boolean) => () => setIsFormOpen(value),
    []
  );

  const handleCreateComment = useCallback(
    async (event: React.FormEvent<HTMLFormElement>) => {
      event.preventDefault();

      const errorsObj = {
        ...Object.keys(fields).reduce(
          (acc, key) => ({
            ...acc,
            [key]:
              key === "email"
                ? fields[key].length >= 3 && fields[key].includes("@")
                : !fields[key as keyof typeof fields].trim(),
          }),
          {}
        ),
      };

      if (Object.values(errorsObj).some(Boolean)) {
        setErrors(errorsObj);

        return;
      }

      try {
        const newComment = await addPostComment({ ...fields, postId: post.id });

        newComment && setComments((prev) => [...prev, newComment]);

        handleToggleOpenForm(false)();
      } catch {
        console.log("can`t add comment");
      }
    },
    [fields, post.id, handleToggleOpenForm]
  );

  const handleDeleteComment = (commentId: number) => async () => {
    try {
      await removePostComment(commentId);

      setComments((prev) => prev.filter((el) => el.id !== commentId));
    } catch {
      console.log("Can't delete comment");
    }
  };

  return (
    <>
      <div className="block">
        <div className="is-flex is-justify-content-space-between is-align-items-center">
          <h2>
            #{post.id}: {post.title}
          </h2>
          <div className="is-flex">
            <span
              className="icon is-small is-right is-clickable"
              onClick={onEditPost}
            >
              <i className="fas fa-pen-to-square"></i>
            </span>
            <span
              className="icon is-small is-right has-text-danger is-clickable ml-3"
              onClick={onDeletePost}
            >
              <i className="fas fa-trash"></i>
            </span>
          </div>
        </div>
        <p data-cy="PostBody">{post.body}</p>
      </div>

      <div className="block">
        {loadingComments && (
          <div className="is-flex is-justify-content-center is-align-items-center mt-2">
            <Loader />
          </div>
        )}

        {!loadingComments && !comments.length && (
          <div className="block">
            <p className="title is-4" data-cy="NoCommentsMessage">
              No comments yet
            </p>
          </div>
        )}

        {!loadingComments &&
          !!comments.length &&
          !isFormOpen &&
          comments.map((el) => (
            <article className="message is-small" data-cy="Comment">
              <div className="message-header">
                <a href={`mailto:${el.email}`} data-cy="CommentAuthor">
                  {el.name}
                </a>
                <button
                  data-cy="CommentDelete"
                  type="button"
                  className="delete is-small"
                  aria-label="delete"
                  onClick={handleDeleteComment(el.id)}
                >
                  delete button
                </button>
              </div>
              <div className="message-body" data-cy="CommentBody">
                {el.body}
              </div>
            </article>
          ))}

        {!loadingComments && !isFormOpen && (
          <button
            data-cy="WriteCommentButton"
            type="button"
            className="button is-link"
            onClick={handleToggleOpenForm(true)}
          >
            Write a comment
          </button>
        )}

        {!loadingComments && isFormOpen && (
          <form onSubmit={handleCreateComment}>
            <InputField
              title="Author Name"
              onChange={handleChangeInputValue}
              error={errors.name}
              value={fields.name}
              leftIcon="fa-user"
              errorText="Name is required"
              name="name"
              placeholder="Name Surname"
            />

            <InputField
              title="Author Email"
              onChange={handleChangeInputValue}
              error={errors.email}
              value={fields.email}
              leftIcon="fa-envelope"
              errorText="Email is required"
              name="email"
              placeholder="Your Email"
            />

            <TextAreaField
              onChange={handleChangeInputValue}
              title="Write comment"
              name="body"
              error={errors.body}
              value={fields.body}
              placeholder="Comment"
              errorText="Comment is required"
            />

            <div className="field is-grouped">
              <div className="control">
                <button type="submit" className="button is-link">
                  Add Comment
                </button>
              </div>
              <div className="control">
                <button
                  type="reset"
                  className="button is-link is-light"
                  onClick={handleToggleOpenForm(false)}
                >
                  Cancel
                </button>
              </div>
            </div>
          </form>
        )}
      </div>
    </>
  );
};

// src/components/PostPreview.vue
<script setup lang="ts">
import { addComment, getComments, removeComment } from "@/assets/api/api";
import type { Comment } from "@/assets/types/Comment";
import type { Post } from "@/assets/types/Post";
import { ref, watch } from "vue";
import Loader from "./Loader.vue";
import AddComment from "./AddComment.vue";

const props = defineProps<{
  post: Post | null;
  handleRemovePost: (postId: number) => void;
  handleOpenEditPost: (post: Post) => void;
}>();

const addingComment = ref(false);
const loadingCommentsError = ref(false);

const commentArr = ref<Comment[] | null>(null);

const comment = ref({ name: "", email: "", body: "" });

watch(
  () => props.post,
  (newPost) => {
    commentArr.value = null;
    loadingCommentsError.value = false;
    if (newPost?.id) {
      getComments(newPost.id)
        .then((res) => {
          commentArr.value = res;
        })
        .catch(() => (loadingCommentsError.value = true));
    }
  },
  { immediate: true }
);

const remove = () => {
  if (props.post?.id) {
    props.handleRemovePost(props.post.id);
  }
};

const edit = () => {
  if (props.post) {
    props.handleOpenEditPost(props.post);
  }
};

const handleRemoveComment = (commentId: number) => {
  commentArr.value = commentArr.value
    ? commentArr.value.filter((el) => el.id !== commentId)
    : null;
  removeComment(commentId);
};

const handleAddComment = () => {
  if (props.post?.id) {
    const commentToSend = {
      postId: props.post?.id,
      name: comment.value.name,
      email: comment.value.email,
      body: comment.value.body,
    };
    addComment(commentToSend)
      .then((res) => {
        commentArr.value ? commentArr.value.push(res) : null;
        comment.value.body = "";
      })
      .finally(() => handleCloseAddComment());
  }
};

const handleOpenAddComment = () => {
  addingComment.value = true;
};

const handleCloseAddComment = () => {
  addingComment.value = false;
};
</script>

<template>
  <div class="tile is-child box is-success flex-itemDown">
    <div class="content">
      <div
        class="is-flex is-justify-content-space-between is-align-items-center"
      >
        <h2 class="title is-4">#{{ post?.id }}: {{ post?.title }}</h2>
        <div class="is-flex">
          <span class="icon is-small is-right is-clickable" @click="edit">
            <i class="fas fa-pen-to-square" />
          </span>
          <span
            class="icon is-small is-right has-text-danger is-clickable ml-3"
            @click="remove"
          >
            <i class="fas fa-trash" />
          </span>
        </div>
      </div>

      <div class="block">
        <p data-cy="PostBody">{{ post?.body }}</p>
      </div>

      <div class="block" v-if="addingComment">
        <AddComment
          :comment="comment"
          :handleAddComment="handleAddComment"
          :handleClose="handleCloseAddComment"
        />
      </div>

      <div class="block" v-else>
        <div v-if="!commentArr" class="block is-flex is-justify-content-center">
          <p class="has-text-danger is-size-4" v-if="loadingCommentsError">
            Loading Error
          </p>
          <Loader v-else />
        </div>

        <p class="title is-4" v-else-if="commentArr?.length === 0">
          No comments yet
        </p>

        <article
          class="message is-small"
          v-for="comment in commentArr"
          :key="comment.id"
        >
          <div class="message-header">
            <a :href="`mailto:${comment.email}`"> {{ comment.name }} </a>
            <button
              type="button"
              class="delete is-small"
              aria-label="delete"
              @click="handleRemoveComment(comment.id)"
            />
          </div>
          <div class="message-body">{{ comment.body }}</div>
        </article>
        <div class="control" v-if="commentArr">
          <button
            type="submit"
            class="button is-link"
            @click="handleOpenAddComment"
          >
            Write a comment
          </button>
        </div>
      </div>
    </div>
  </div>
</template>
