// src/components/Sidebar/index.tsx
import { FC } from "react";
import cn from "classnames";

import "./index.css";

interface Props {
  Component: React.ReactElement | null;
}

export const Sidebar: FC<Props> = ({ Component }) => {
  return (
    <div
      className={cn("tile is-parent is-8-desktop Sidebar", {
        "Sidebar--open": !!Component,
      })}
    >
      <div className="tile is-child box is-success ">
        <div className="content">{Component}</div>
      </div>
    </div>
  );
};

// src/components/sidebar/index.vue
<script setup>
const { isOpen } = defineProps(['isOpen']);
</script>

<template>
  <div class="tile is-parent is-8-desktop Sidebar" :class="{ 'Sidebar--open': isOpen }">
    <div class="tile is-child box is-success ">
      <div class="content">
        <slot></slot>
      </div>
    </div>
  </div>
</template>

<style src="./index.css" scoped></style>
