// src/components/modules/Header.vue
<script setup>
import { useUserStore } from '../../stores/userStore';
import { useRouter } from 'vue-router';

const router = useRouter();
const userStore = useUserStore();
const userName = userStore.user.name;

const handleLogout = async () => {
  userStore.logout();
  await router.push('/login');
};
</script>

<template>
  <nav class="navbar" role="navigation" aria-label="main navigation">
    <div class="navbar-item">
      <h2 class="title is-size-4">Vue List Of Posts</h2>
    </div>
    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
          <div class="mr-5 mb-2">
            <p>User: {{ userName }}</p>
          </div>

          <a class="button is-light" @click="handleLogout"> Logout </a>
        </div>
      </div>
    </div>
  </nav>
</template>

// src/shared/Header/index.tsx
import { FC, useCallback } from "react";
import { useNavigate } from "react-router-dom";

import { getUserFromLS } from "utils/getUser";

export const Header: FC = () => {
  const user = getUserFromLS();
  const navigate = useNavigate();

  const handleLogout = useCallback(() => {
    localStorage.removeItem("user");

    navigate("/login");
  }, [navigate]);

  if (!user) {
    return null;
  }

  return (
    <nav className="navbar" role="navigation" aria-label="main navigation">
      <div className="navbar-item">
        <h1 className="title is-size-4">Vue List Of Posts</h1>
      </div>
      <div className="navbar-end">
        <div className="navbar-item">
          <div className="buttons">
            {user && (
              <div className="mr-5 mb-2">
                <p>User: {user.name}</p>
              </div>
            )}
            <a className="button is-light" onClick={handleLogout}>
              Logout
            </a>
          </div>
        </div>
      </div>
    </nav>
  );
};
