// src/routes/login/index.tsx
import { useState } from "react";
import { useNavigate } from "react-router-dom";
import classNames from "classnames";

import { createUser, getUserByEmail } from "api";

export const Login = () => {
  const navigate = useNavigate();

  const [email, setEmail] = useState("");
  const [name, setName] = useState("");

  const [needToRegister, setNeedToRegister] = useState(false);
  const [loading, setLoading] = useState(false);
  const [errorMessage, setErrorMessage] = useState("");

  const saveUser = (user: User.Data) => {
    localStorage.setItem("user", JSON.stringify(user));
  };

  const register = async () => {
    try {
      const user = await createUser({ name, email });

      user && saveUser(user);
    } catch (err) {
      setErrorMessage("Can't create a user");
    }
  };

  const checkEmail = async () => {
    try {
      const existingUser = await getUserByEmail(email);

      existingUser ? saveUser(existingUser) : setNeedToRegister(true);
    } catch (err) {
      setErrorMessage("Can't create a user");
    }
  };

  const handleSubmit = async (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();

    setLoading(true);

    const callback = needToRegister ? register : checkEmail;

    await callback();

    setLoading(false);
    navigate("/");
  };

  return (
    <section className="container is-flex is-justify-content-center	">
      <form onSubmit={handleSubmit} className="box mt-5">
        <h1 className="title is-3">
          {needToRegister ? "You need to register" : "Get your userId"}
        </h1>

        <div className="field">
          <label className="label" htmlFor="user-email">
            Email
          </label>

          <div
            className={classNames("control has-icons-left", {
              "is-loading": loading,
            })}
          >
            <input
              type="email"
              id="user-email"
              name="email"
              className={classNames("input", {
                "is-danger": !needToRegister && errorMessage,
              })}
              placeholder="Enter your email"
              disabled={loading || needToRegister}
              value={email}
              required
              onChange={(e) => setEmail(e.target.value)}
            />

            <span className="icon is-small is-left">
              <i className="fas fa-envelope" />
            </span>
          </div>

          {!needToRegister && errorMessage && (
            <p className="help is-danger">{errorMessage}</p>
          )}
        </div>

        {needToRegister && (
          <div className="field">
            <label className="label" htmlFor="user-name">
              Your Name
            </label>

            <div
              className={classNames("control has-icons-left", {
                "is-loading": loading,
              })}
            >
              <input
                type="text"
                id="user-name"
                name="name"
                className={classNames("input", {
                  "is-danger": needToRegister && errorMessage,
                })}
                placeholder="Enter your name"
                required
                minLength={4}
                disabled={loading}
                value={name}
                onChange={(e) => setName(e.target.value)}
              />

              <span className="icon is-small is-left">
                <i className="fas fa-user" />
              </span>
            </div>

            {needToRegister && errorMessage && (
              <p className="help is-danger">{errorMessage}</p>
            )}
          </div>
        )}

        <div className="field">
          <button
            type="submit"
            className={classNames("button is-primary", {
              "is-loading": loading,
            })}
          >
            {needToRegister ? "Register" : "Login"}
          </button>
        </div>
      </form>
    </section>
  );
};

// src/components/login/LoginComponent.vue
<script lang="ts">
import { createUser, getUserByEmail } from '../../api/api';
import { defineComponent, type PropType } from 'vue';
import type { User } from '../../types/User';
import NeedToRegister from '../inputs/NeedToRegister.vue';

export default defineComponent({
  components: {
    NeedToRegister,
  },
  props: {
    user: {
      type: Object as PropType<User | null>,
      required: true, 
    },
  },
  emits: ['update:user'],
  data() {
    return {
      start: true,
      email: '',
      name: '',
      isLoading: false,
      isErrorMessage: '',
    }
  },
  methods: {
    handleSubmit() {
      this.isLoading = true;
      this.isErrorMessage = '';

      if (this.start) {
        getUserByEmail(this.email)
          .then(({ data }) => {
            if (data[0]) {
              this.$emit('update:user', data[0]);
              localStorage.setItem('user', JSON.stringify(data[0]));
            }

            this.start = false;
          })
          .catch(() => this.isErrorMessage = 'Unable to get user. Please try again later.')
          .finally(() => this.isLoading = false);
      }

      if (!this.start) {
        createUser(this.email, this.name)
          .then(({ data }) => {
            this.$emit('update:user', data);
            localStorage.setItem('user', JSON.stringify(data));
          })
          .catch(() => this.isErrorMessage = 'Unable to create a user. Please try again later.')
          .finally(() => this.isLoading = false)
      }
    },
  }
})
</script>

<template>
  <section class="container is-flex is-justify-content-center">
    <form @submit.prevent="handleSubmit" class="box mt-5"> 
      <h1 v-show="start" class="title is-3">Get your userId</h1>
      <h1 v-show="!start && !user" class="title is-3">You need to register</h1>

      <div class="field">
        <label class="label" htmlFor="user-email"> Email </label>

        <div class="control has-icons-left">
          <input
            type="email"
            id="user-email"
            name="email"
            class="input"
            placeholder="Enter your email"
            v-model="email"
            :disabled="!start && !user"
            required
          />

          <span class="icon is-small is-left">
            <i class="fas fa-envelope" />
          </span>
        </div>
      </div>

      <NeedToRegister 
        v-if="!start && !user" 
        v-model:name="name"
      />

      <p v-show="isErrorMessage" class="help is-danger mb-4">{{ isErrorMessage }}</p>

      <div class="field">
        <button 
          type="submit" 
          class="button is-primary"
          :class="{ 'is-loading': isLoading, }"
        >
          Login
        </button>
      </div>
    </form>
  </section>
</template>
