// vue_dynamic_list_of_posts/src/components/PostsList.vue
<script setup lang="ts">
import type { Post } from '../types/Post'

const props = defineProps<{
  posts: Post[],
  showAddPostForm: boolean,
  selectedPost: Post | null,
  isPostEditing: boolean,
}>()

const emit = defineEmits(['togglePost', 'openAddPostForm'])

const togglePost = (post: { id: number; title: string; body: string }) => {
  emit('togglePost', post)
}
</script>

<template>
  <div class="tile is-parent">
    <div class="tile is-child box is-success">
      <div class="block">
        <div class="is-flex is-justify-content-space-between mb-5">
          <p class="title m-0">Posts</p>
          <button
            type="button"
            class="button is-link p-2"
            @click="$emit('openAddPostForm')"
            :disabled="showAddPostForm"
          >
            Add New Post
          </button>
        </div>

        <table class="table is-fullwidth is-striped is-hoverable is-narrow">
          <thead>
            <tr class="has-background-link-light">
              <th>ID</th>
              <th>Title</th>
              <th class="has-text-right">Actions</th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="{ id, title, body } in posts" :key="id">
              <td>{{ id }}</td>
              <td>{{ title }}</td>
              <td class="has-text-right is-vcentered">
                <button
                  type="button"
                  :class="id === selectedPost?.id && !isPostEditing ? 'button is-link' : 'button is-light'"
                  @click="
                    togglePost({
                      id,
                      title,
                      body
                    });
                    console.log(isPostEditing)
                  "
                >
                 {{ id === selectedPost?.id && !isPostEditing ? 'Close' : 'Open' }}
                </button>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</template>

// src/components/PostsList/index.tsx
import { FC } from "react";
import cn from "classnames";
import { Loader } from "shared/Loader";

interface Props {
  onOpenClosePost: (post: number) => () => void;
  openPostId: number | null;

  onOpenNewPostForm: (value: boolean) => () => void;
  isOpenNewPostForm: boolean;

  posts: Posts.Data[];
  isLoading: boolean;
}

export const PostsList: FC<Props> = ({
  onOpenClosePost,
  openPostId,
  isOpenNewPostForm,
  onOpenNewPostForm,
  posts,
  isLoading,
}) => (
  <div className="tile is-parent">
    <div className="tile is-child box is-success">
      <div className="block">
        <div className="block is-flex is-justify-content-space-between">
          <p className="title">Posts</p>
          <button
            type="button"
            className={cn("button is-link", {
              "is-light": isOpenNewPostForm,
            })}
            onClick={onOpenNewPostForm(true)}
          >
            Add New Post
          </button>
        </div>
        {isLoading ? (
          <div className="is-flex is-justify-content-center is-align-items-center mt-2">
            <Loader />
          </div>
        ) : (
          <table className="table is-fullwidth is-striped is-hoverable is-narrow">
            <thead>
              <tr className="has-background-link-light">
                <th>ID</th>
                <th>Title</th>
                <th className="has-text-right">Actions</th>
              </tr>
            </thead>
            <tbody>
              {posts.map((el) => (
                <tr key={el.id}>
                  <td>{el.id}</td>
                  <td>{el.title}</td>
                  <td className="has-text-right is-vcentered">
                    <button
                      type="button"
                      className={cn("button is-link", {
                        "is-light": openPostId !== el.id,
                      })}
                      onClick={onOpenClosePost(el.id)}
                    >
                      {openPostId === el.id ? "Close" : "Open"}
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </div>
    </div>
  </div>
);
